# Generated by Django 4.1.2 on 2022-12-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_adress_owners_products_shop_shopproducts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='created',
            field=models.DateField(default=None),
        ),
    ]
