# Generated by Django 4.1.2 on 2023-02-04 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0005_rename_owner_shop_ownerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='ownerProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
