# Generated by Django 4.1.2 on 2023-03-02 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_alter_shop_ownerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
