# Generated by Django 4.1.2 on 2023-03-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='created',
        ),
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(default='defaultShop.jpg', upload_to='shop_pic'),
        ),
    ]
